# Generated by Django 2.2 on 2019-12-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0008_auto_20191228_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='img/default.png', null=True, upload_to='img/'),
        ),
    ]
