# Generated by Django 2.2 on 2019-12-30 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0011_auto_20191229_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pk', '-updated', '-publish_time', '-timestamp']},
        ),
    ]
