# Generated by Django 2.2 on 2019-12-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0005_auto_20191228_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
