# Generated by Django 2.2 on 2019-12-28 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0006_auto_20191228_0827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publish_time', '-updated', '-timestamp']},
        ),
    ]
