# Generated by Django 2.2 on 2019-12-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0007_auto_20191228_0836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pk', '-publish_time', '-updated', '-timestamp']},
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.png', null=True, upload_to='img/'),
        ),
    ]
