# Generated by Django 2.2 on 2019-12-30 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0012_auto_20191230_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pk', '-updated', '-timestamp']},
        ),
    ]
